# 난수

## #01. 작업준비

### 패키지 참조

In [1]:
import tensorflow as tf

## #02. 균등 분포 난수

일반적으로 각 이벤트의 결과값을 알 수 없는 경우 미래에 발생할 이벤트의 결과값 $x$가 각 예상되는 범위별로 균등한 확률로 일어날 것이라고 예상될 때 사용.

### 1) 균등 분포 난수의 사용 예

#### 주사위에 대한 확률

- 200번을 던지고 201번째  주사위를 던진다고 했을 때 201번째 결과값은 앞의 1에서 200번까지 결과값에 영향을 받지 않는다.
- 201번째 결과값이 1,2,3,4,5,6 각각의 결과값으로 나올 확률은 6분의 1이며 이는 앞의 1~200번째 결과값에 영향을 받아 줄어들거나 늘어나지 않는다는 것이다.
- 이처럼 미래 결과값이 경험적으로 알 수 없을 상황에서 사용하는 것이 균등분포이다.

### 2) 균등 분포 난수 실험

#### 스칼라 형태의 균등 분포 난수

In [8]:
# 난수 생성
uni_rnd1 = tf.random.uniform(shape=[], minval=0, maxval=100, dtype=tf.int32)
tf.print(uni_rnd1)

44


#### 백터 형태의 균등 분포 난수 - 1차원

In [14]:
# 벡터 형태로 난수 생성
uni_rnd2 = tf.random.uniform(shape=[5], minval=0, maxval=100, dtype=tf.int32)
tf.print(uni_rnd2)

[14 15 94 3 92]


#### 행렬 형태의 균등 분포 난수 - 2차원

In [15]:
# 행렬 형태의 난수 생성
uni_rnd3 = tf.random.uniform(shape=[2,3], minval=0, maxval=100, dtype=tf.int32)
tf.print(uni_rnd3)

[[63 66 99]
 [15 96 34]]


#### 텐서 형태의 균등 분포 난수 - 3차원

In [16]:
# 텐서 형태의 난수 생성
uni_rnd4 = tf.random.uniform(shape=[2,3,4], minval=0, maxval=100, dtype=tf.int32)
tf.print(uni_rnd4)

[[[85 29 21 10]
  [91 14 38 17]
  [72 94 47 38]]

 [[44 75 44 13]
  [8 13 51 20]
  [70 91 47 43]]]


### 3) 렌덤값을 갖는 행렬 곱 예시

#### 랜덤값을 갖는 3행2열의 행렬을 변수 x로 정의

In [17]:
# uniform([3, 2]) -> 3행 2열
x = tf.Variable(tf.random.uniform([3, 2]))
tf.print(x)

[[0.331782341 0.205891728]
 [0.267096281 0.420716882]
 [0.0198105574 0.825423479]]


#### 랜덤값을 갖는 2행1열의 행렬을 변수 y로 정의

In [18]:
# uniform([2, 1]) -> 2행 1열
y = tf.Variable(tf.random.uniform([2, 1]))
tf.print(y)

[[0.856167555]
 [0.906526685]]


#### `행렬곱`에 대한 연산을 수행하는 노드 정의

In [19]:
# x-3행 2열, y-2행 1열
expr = tf.matmul(x, y)
tf.print(expr)

[[0.470707625]
 [0.610070229]
 [0.765229583]]


## #03. 정규 분포 난수

정규분포란 과거의 축적된 경험적 데이터를 이미 보유하고 있는 상태에서 이용하여 미래에 발생할 결과값 $x$의 각 예상되는 범위별로 발생될 확률을 어느 정도 추정할 수 있을 때 사용

### 1) 정규 분포 난수의 사용 예

#### 매장의 매출액 예측

- 이전 3개월의 매출이 2천만원, 2천백만원, 2천2백원 발생한 경우 평균이나 범위에 대한 예측이 가능하다.
- **`평균`에 대한 예측** → 이번달 매출은 과거 3개월의 매출평균인 2천백만원으로 예측.
- **`범위`에 대한 예측** → 최소 2천만원 ~  최대 2천2백만원까지 매출이 발생할 수 있다는 예상이 가능함.

#### 로또 추첨

- 64개의 공 중에서 하나를 랜덤으로 추출하면, 두 번째 랜덤 범위는 첫 번째 추출된 공을 제외한 범위 안에서 생성된다.
- 만약 로또 추첨시 하나의 공을 뽑아 번호를 확인하고 그 공을 다시 추첨 대상에 포함시켰다면 균등분포 난수가 된다.

### 2) 정규 분포 난수 실험

`정규 분포 난수`를 생성할 때는 `평균(mean)과 표준편차(stddev)를 지정`해야 한다.

#### 스칼라 형태의 정규 분포 난수

In [21]:
# 차원(랭크)가 0
normal_rnd1 = tf.random.normal(shape=[], mean=0.0, stddev=1.0)
tf.print(normal_rnd1)

-1.04369843


#### 백터 형태의 정규 분포 난수

In [22]:
# shape=[5] -> 5열
uni_rnd2 = tf.random.normal(shape=[5], mean=0.0, stddev=1.0)
tf.print(uni_rnd2)

[1.34755969 -0.2438346 -0.0720280707 0.2487562 0.0944584534]


#### 행렬 형태의 정규 분포 난수

In [23]:
# shape=[2,3] -> 2행 3열
normal_rnd3 = tf.random.normal(shape=[2,3], mean=0.0, stddev=1.0)
tf.print(normal_rnd3)

[[0.199062929 2.21989489 2.13130331]
 [1.6405834 0.00508371694 0.803399801]]


#### 텐서 형태의 정규 분포 난수

In [24]:
# shape=[2,3,4] -> 2개의 3행 4열
normal_rnd4 = tf.random.normal(shape=[2,3,4], mean=0.0, stddev=1.0)
tf.print(normal_rnd4)

[[[-1.10132 -0.883835733 -0.66920197 0.252384126]
  [-0.170888498 0.421493322 0.831888318 -0.795214474]
  [0.151588142 -0.436711133 0.670097888 -0.319718748]]

 [[-0.47072807 -0.940027356 -2.19026566 -1.82446265]
  [1.07938337 -0.815032125 -0.758381546 3.10527587]
  [0.0803181753 -1.53447735 -0.0811417252 0.707211435]]]
